name: Rekognition PR Analysis (Beta)

on:
  pull_request:
    branches:
      - main

jobs:
  analyze_image:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DYNAMO_TABLE: ${{ secrets.DYNAMODB_TABLE_BETA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3

      - name: Run Rekognition Analysis Script
        run: python analyze_image.py
